---
title: "InClass_Quiz3_Meyer"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

“All work presented is my own. I have not communicated with or worked with anyone else on this quiz.”

Trent Meyer

# Question 1:
1. You go to your GitHub site and make a change to the README file (adding a sentence, for example).
2. In R Studio, you update one of your .Rmd files, adding a line of code and commit the file.
3. You attempt to push the new file to your GitHub site.

Once you get to the third step, you’ll get an error when you try to push. Why? What do you need to do first before you make the push in Step 3?

You must first change the README file in your Rstudio. Your Git branch will be ahead of your R project, and you must reflect those changes into your Rstudio so it is caught up.

# Question 2: Give 2 advantages of using Git and GitHub. These must be advantages that we discussed in class (so you should not simply google “advantages of Git” and give the first two things that pop up).

With Git, you are able to see previous versions of your code, so if you messed up you can go to the last working version and start from there. It also allows other people to see your code and projects, which on R alone is pretty difficult. Collaborating through Git is much easier, as you can add collaborators who can see any updates you made and when.

# Question 3: Choose 1 of the 12 principles of the ethical practice of data science that you think is the most difficult to execute. Give a short, possibly hypothetical, example that illustrates how that principle could be difficult to follow.

Principle 9 says, "Consider carefully the ethical implications of choices we make when using data, and the impacts of our work on individuals and society." This is the most difficult in my opinion because we must think ahead to see how our data could impact others. It could immediately impact a group, or cause another to lose funding because of the data presented.

# Question 4: The authors of Data Feminism argued that data scientists should “embrace emotion,” not ignore it when building visuals. State the example that the authors used to show how emotion can be used to make a visual stronger. Then, give an argument against “embracing emotion.” In other words, give an argument that data visualizations should be devoid of emotion as much as possible, even if that’s not what you believe.

They used the example of gun violence, and showing the number of years lost because of a certain act. Embracing emotion may not be the best thing to do however, and I think that data visualizations that are in a political sense, just need to show data, not really get into emotions that could stray the viewers away from the thing they want to see. 

